# Build settings
baseurl: /
markdown: kramdown
theme: minima
destination: ./_site
permalink: /:year/:month/:day/:title
excerpt_separator: "<!-- excerpt end -->"

# Site settings
title: Daniel Näslund
description: "A blog about security, embedded and performance optimization"

url: "https://dannas.name"
github_username: dannas
mastodon:
  - username: dannas
  - instance: fosstodon.org

# Plugins
gems:
  - jekyll-seo-tag

