# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
excerpt_separator: "<!-- excerpt end -->"

# Site settings
title: Daniel Näslund
description: "A blog about security, embedded and performance optimization"
url: "https://dannas.name"
author:
  name: "Daniel Näslund"
  email: "dannas@dannas.name"
  url: "https://dannas.name"


# Markdown Settings
kramdown:
    toc_levels: 1..3
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
